### PR TITLE
Update myprofile_list.html

### PR DESCRIPTION
**Pull request by Priyansh2001here**
updated ajax view #20

### CODE REVIEW

**Comment by smitbarmase** [comment]
@Priyansh2001here  
Nice work! You have made 3 pull requests for the same issue #20 
We recommend making a new pull request comprising of all these changes so that we can review your work at ease.
We will close these 3 pull requests, once your new pull request received.

Suggestion: Next time, try making multiple commits, in the same pull request. :)

**Comment by Priyansh2001here** [comment]
ok

**Comment by smitbarmase** [comment]
@Priyansh2001here any updates?

**Comment by smitbarmase** [comment]
New PR is created #30. Review in progress.

**Pull request closed without merging**
