### PR TITLE
Footer to bottom of viewport & its link cursor is solved :bug:

### PR DESCRIPTION
**Pull request by SuNiL-Chau**

### CODE REVIEW

**Comment by smitbarmase** [comment]
issue
The footer position is not proper.

**Comment by SuNiL-Chau** [comment]
Can you tell me which page it is?

**Comment by smitbarmase** [comment]
/accounts/password/reset

**Comment by SuNiL-Chau** [comment]
but this directory appears after logging in to the account if I'm not wrong?

**Pull request closed without merging**
